// <auto-generated />
using Laba4EF.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using AppContext = Laba4EF.DBContext.AppContext;

#nullable disable

namespace Laba4EF.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20221117011350_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Laba4EF.Tables.FirstTable", b =>
                {
                    b.Property<int>("gameID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("gameID"));

                    b.Property<string>("criticCount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("criticScore")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("developer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("platform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("publisher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rating")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userCount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userScore")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("yearOfRelease")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("gameID");

                    b.ToTable("FirstTable");
                });
#pragma warning restore 612, 618
        }
    }
}
